### ISSUE TITLE
English lessons policy

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/playbook#100]
This is missing!

**Comment by aldesantis** [comment]
@kennyadsl what would you add and wherE?

**Comment by kennyadsl** [comment]
Sorry, you are right, this issue is terrible! 😬 

I'd like to add some text about English lessons that we offer to everyone on the team. It's probably content for the personal growth section, or benefits page. 

The issue here is that it's not clear that everyone can use iTalki paid by Nebulab and how. Another thing to clarify that this could be done during working hours, since some of us thought that lessons should be done after work.

**Comment by aldesantis** [comment]
Okay, will take care of it!
