### ISSUE TITLE
Playbook publication

### ISSUE THREAD

**Issue by mdesantis** [nebulab/playbook#114]
As agreed with @kennyadsl, I'm starting researching about playbook publication. This issue is meant to keep progress about that. /cc @mtylty

**Comment by mdesantis** [comment]
Looking around for inspirations, a very similar thing is GitLab handbook: https://about.gitlab.com/handbook/

What I like:

- the search field above: IMHO very useful when you have some doubt about something but you don't remember where is it

What I don't like:

- the theme: too raw. I'd prefer something a bit more polished, e.g. https://stimulusjs.org/handbook/introduction

**Comment by mdesantis** [comment]
Mockups link (for reference): https://invis.io/BFQ1FI88NZH#/343664905_Overview_vs-_D

**Comment by aldesantis** [comment]
🎉
