### ISSUE TITLE
Update Playbook section

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/playbook#146]
https://playbook.nebulab.it/working-on-nebulab/#playbook

^ this section makes no more sense with the new playbook. We should also update here with instruction about how to edit the Playbook. ref #145

**Comment by aldesantis** [comment]
@kennyadsl why doesn't it make sense? It seems still relevant to me:

> This repository evolves continuously. We all need to contribute to it in order for it to be the point of reference for any doubts on Nebulab and our process.
>
> If you have any ideas for additions, improvement, or if you noticed a mistake, feel free to open an issue or a pull request!

We just need to add instructions on how to work with the CMS, but developers can still use GitHub so the PR workflow still works as before.

**Comment by kennyadsl** [comment]
Sorry, I meant that it does not make sense to talk about `this repository` since, when it is read on the playbook website, it is not a repository. We should find a copy that plays well with both things IMO.
