### ISSUE TITLE
Rename Processes to People Ops

### ISSUE THREAD

**Issue by aldesantis** [nebulab/playbook#155]
Currently, the Processes section is basically a catch-all for any content we're not sure where to put. There's no clear structure which makes the section hard to navigate.

## Option 1

A possible way to organize the content would be to create a new "Administrivia" section containing all content regarding policies and paperwork, such as:

- Resignation
- Travel policy
- Paid time off and overtime
- Payroll
- Workplace health and safety

In Processes, we would put all other company processes that are not strictly bureaucratic.

## Option 2

When you look at it, the content that is currently in Processes is really just HR stuff. If we rename Processes to People Operations, we should be good to go without having to add a new section.

Also, we should split content by concept (e.g. People Operations, Development)., not by type (e.g. Processes).

**Comment by matteogalliani** [comment]
Thanks, @aldesantis. IMO we should go with Option 2 🎸🤘
