### ISSUE TITLE
Lista di servizi cloud usati spesso

### ISSUE THREAD

**Issue by aldesantis** [nebulab/playbook#16]
- Collezione dei log: ?
- Exception monitoring: Honeybadger/New Relic
- Email delivery: ?
- ...

**Comment by mtylty** [comment]
Non sono molto convinto di voler aggiungere una lista di servizi...

Cambierebbe molto spesso e succede che usiamo delle cose per noi ed i clienti hanno altre preferenze e usano altri tool.

Poi di fatto stiamo lavorando parecchio per formalizzare una lista che se vai a vedere è al 90% AWS. Ha rilevanza scriverlo... non so, discutiamone.

**Comment by aldesantis** [comment]
No, sono d'accordo che non serva, ho cambiato idea. 😄
