### ISSUE TITLE
Press Kit Link

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/playbook#167]
Moving to Netlify CMS we've lost the link to the Press Kit, that was onl present in the README as a direct link: 

https://drive.google.com/drive/folders/1VATPcbAhnhHZ376_GPixyYAo6u3gN8Os

Is there a way to have it back?

**Comment by mfrecchiami** [comment]
Actually add Press Kit like a topic as other, should be a solution. So we can give a preview of the press kit folder's content by adding a list; furthermore we can add links to the specific folders such as Fonts, Logo, Video, Wallpaper
