### ISSUE TITLE
Relax rules on remote office space

### ISSUE THREAD

**Issue by aldesantis** [nebulab/playbook#197]
Our current policy about the office space of our remote workers states that:

> This space must be specific, quiet, free of distraction and other people.

In hindsight, this is a bit too strict, as it doesn't leave room for working out of coffee shops, which can sometimes be a nice change of scenery and helps fight loneliness for those who work remotely. Some people even work better with the white noise of a coffee shop in the background!

With that said, it wouldn't be okay, for instance, to take a call from a coffee shop, so we must make that clear.

After some consideration, we believe the best compromise is to change the policy above to indicate that your office space, whatever it is, must simply allow you to complete the day's work without any disruptions to your or your colleagues' productivity.

## Todo

- [x] I have added this issue to the [Workflow](https://github.com/nebulab/playbook/projects/1) GitHub project.
- [x] I have added the appropriate labels to this issue.

**Comment by mdesantis** [comment]
I agree, I worked in some coffee shops sometimes and it was surprisingly a wonderful experience from the concentration point of view, coffe shop sounds even helped me focusing
