### ISSUE TITLE
Redirect first-level chapters to first section

### ISSUE THREAD

**Issue by mtylty** [nebulab/playbook#205]
Right now we can't link first-level chapters like this: https://playbook.nebulab.it/client-guide because it will end up in a 404.

I think we can easily redirect with middleman from the first subsection (i.e. https://playbook.nebulab.it/client-guide/onboarding/ for the client-guide).

## Todo

- [x] I have added this issue to the [Workflow](https://github.com/nebulab/playbook/projects/1) GitHub project.
- [x] I have added the appropriate labels to this issue.

**Comment by aldesantis** [comment]
@mtylty I think this would be great. Since Middleman can only do HTML redirects, perhaps it would be better to redirect at the Netlify level via `_redirects`?
