### ISSUE TITLE
Add anchor links to sections titles

### ISSUE THREAD

**Issue by mdesantis** [nebulab/playbook#208]
I think we should add anchor links to sections titles.

For example, if I want to share with someone "Choosing conferences", which is a title of [Travel policy section](https://playbook.nebulab.it/people-ops/travel-policy/), currently I would share the link and tell someone "scroll until you find "Choosing conferences" section. With anchor links to titles instead I could just share a link similar to the following: https://playbook.nebulab.it/people-ops/travel-policy#choosing-conferences.

## Todo

- [ ] I have added this issue to the [Workflow](https://github.com/nebulab/playbook/projects/1) GitHub project.
- [x] I have added the appropriate labels to this issue.

**Comment by mfrecchiami** [comment]
I agree with you @mdesantis; maybe we should add also an hover effect on the anchor titles, like Github do: 

<img width="271" alt="Schermata 2019-06-26 alle 12 37 45" src="https://user-images.githubusercontent.com/46188345/60173525-3c977100-980f-11e9-8734-b34844de4ae1.png">

@davidedistefano do you remember that we already talked about this issue?

**Comment by davidedistefano** [comment]
@mfrecchiami Yes, we already talked about this as a possible UX improvement. This library may come in handy https://clipboardjs.com/ by the way.
