### ISSUE TITLE
Create a library of suggested readings for mentors and team leads

### ISSUE THREAD

**Issue by aldesantis** [nebulab/playbook#287]
TBD.

**Comment by mtylty** [comment]
What if we point people to this? https://github.com/LappleApple/awesome-leading-and-managing

**Comment by filippoliverani** [comment]
> What if we point people to this? https://github.com/LappleApple/awesome-leading-and-managing

It would be even better if could add our own (distilled) reading list, maybe one for every role

**Comment by aldesantis** [comment]
We started doing this in the team leads section, I think we should just do something similar for mentors and start expanding it.
