### ISSUE TITLE
Policy in caso di assenza in un giorno lavorativo sul cliente

### ISSUE THREAD

**Issue by matteogalliani** [nebulab/playbook#29]
In [Crescita personale](https://github.com/nebulab/playbook/blob/master/crescita-personale/venerdi.md) si legge:

># Il venerdì
>
>Il venerdì in Nebulab è un momento di crescita personale e collettiva. Il venerdì non lavoriamo sui
clienti, ma su noi stessi e di conseguenza su Nebulab.

Manca la policy in caso di assenza per ferie o giorno festivo durante i 4 giorni in cui lavoriamo per i clienti.

**Comment by MinasMazar** [comment]
Aggiungerei la stessa informazione anche nella sezione [Lavorare per i clienti](https://github.com/nebulab/playbook/tree/master/lavorare-per-i-clienti) (forse in consuntivazione?)
