### ISSUE TITLE
Lavorare da casa

### ISSUE THREAD

**Issue by matteogalliani** [nebulab/playbook#30]
In [Dove e quando](https://github.com/nebulab/playbook/blob/master/lavorare-insieme/dove-e-quando.md) si legge:

>Riguardo al luogo la flessibilità è ancora maggiore. Nebulab al momento ha due sedi operative, una a Pescara e una a Latina, ma si è liberi di lavorare ovunque si voglia (volendo anche da casa propria).

Aggiungerei un paragrafo dal titolo `Lo spazio di lavoro a casa` dove chiarire come creare un ambiente di lavoro ideale anche a casa propria.

**Comment by kennyadsl** [comment]
Policy:

- benefit? anche, ma principalmente un incentivo alla produttività
- permesso in caso si hanno impegni (tipo tecnico a casa)
- postazione uguale a quella dell'ufficio
- niente distrazioni quando si sta a casa
- spazio isolato
