### ISSUE TITLE
[Bug] Broken Matrix Link competency-matrix.html.md

### ISSUE THREAD

**Issue by severinkehding** [nebulab/playbook#327]
Hey guys,

while reading the playbook I did notice that the Link "Nebulab Competency Matrix" in the sentence:

_After looking at a few examples, we designed our own matrix, which you can find here: Nebulab Competency Matrix._

is broken. 

Cheers

Sev

## Todo

- [ ] I have added this issue to the [Workflow](https://github.com/nebulab/playbook/projects/1) GitHub project.
- [ ] I have added the appropriate labels to this issue.

**Comment by kennyadsl** [comment]
Thanks for reporting, we'll address this as soon as possible!

**Comment by severinkehding** [comment]
Damn, that was quick as hell. In the meantime I will prep my documents to apply at Nebulab.

Hope to speak soon <3
