### ISSUE TITLE
Fix broken GitHub links in blog page

### ISSUE THREAD

**Issue by garciajordy** [nebulab/playbook#346]
**The GitHub links in the [blog](https://playbook.nebulab.com/working-on-nebulab/blog/) page are not working.**
- The first link is located in the [Writing & Publishing Process](https://playbook.nebulab.com/working-on-nebulab/blog/#writing--publishing-process) section in the second list item.  See the provided image.

 ![image](https://user-images.githubusercontent.com/74253475/120924343-01c93380-c6dc-11eb-9bba-863d0459b3e4.png) 

- The second link is located in the [Guidelines for writing](https://playbook.nebulab.com/working-on-nebulab/blog/#guidelines-for-writing) section in the fourth (last) list item. See the provided image.

![image](https://user-images.githubusercontent.com/74253475/120924640-38ec1480-c6dd-11eb-92f5-1ba091ab50b9.png)

_The links are giving a 404 not found page on GitHub_

**Comment by mtylty** [comment]
Hey @garciajordy, I don't see any 404s on the links you provided, can you elaborate a bit mode?

**Comment by garciajordy** [comment]
> Hey @garciajordy, I don't see any 404s on the links you provided, can you elaborate a bit mode?

I made a video showing what happens exactly when I press those links.
https://www.loom.com/share/56223571fd2546b7802b21ccfbc26acd

**Comment by garciajordy** [comment]
Is it maybe the **nebulab-website** that changed the name?

**Comment by matteogalliani** [comment]
@mtylty @garciajordy that playbook page links to a private repo `nebulab/nebulab-website`.
We can't make the website's repo public at the moment, but we can evaluate if we want to share writing tips in another place in the future.

@garciajordy, thanks for flagging this possible issue. I'm closing it.

**Comment by mtylty** [comment]
@garciajordy sorry about that 😂... I completely forgot our website is private, it must be Monday 🤷.

@matteogalliani thanks for closing the issue.

**Comment by garciajordy** [comment]
> @garciajordy sorry about that 😂... I completely forgot our website is private, it must be Monday 🤷.
> 
> @matteogalliani thanks for closing the issue.

Oh, ok too bad. It looks interesting!
