### ISSUE TITLE
BEM best practices

### ISSUE THREAD

**Issue by davidedistefano** [nebulab/playbook#40]
L'idea è quella di creare una guida sul Playbook per tutto il team Front-End da usare come standard.

Si potrebbe partire da questo articolo:
https://www.smashingmagazine.com/2018/06/bem-for-beginners/

**Comment by davidedistefano** [comment]
Commento di Francesco:

- *Non utilizzare i selettori di tag*: vero, la struttura HTML molto spesso cambia durante lo sviluppo quindi se si hanno selettori di tag quasi sicuramente si spacca qualcosa ogni volta che cambia il markup.
A volte può capitare che per pigrizia, per la fretta o per la certezza che la struttura non potrà mai cambiare si usino i tag (io per primo, se guardate Tamo o KasaKaffè trovate vari orrori di questo tipo) ma d'ora in poi evitiamo.

- *Niente CSS reset*: vero, alla fine si fa l'override dell'override quindi oltre ad essere inutile si aggiunge del codice in più.

- *Selettore universale*: Ni, basta solo non abusarne. Io solitamente lo uso solamente per impostare il `box-model` e l'`outline` degli elementi (il bordo colorato attorno agli elementi in focus):
```
* {
  box-sizing: border-box;
  outline: none
}

```
Così io dico che è accettabile, non impatta niente del layout.

- *Selettori innestati*: Usando BEM come si deve dovrebbero sparire da soli. Poi ovvio che nessuno li vieta, ma più si innesta più tempo impiega il browser a parsare.

- *Combinare classi, tag, id, ecc. nei selettori*: Vero, ad ogni tipo di elemento nel selettore viene assegnato una sorta di punteggio. Più questo punteggio è alto (quindi più selettori ci sono) più il selettore viene applicato dopo.
Non è raro che una regola venga overridata senza apparentemente motivo da un'altra regola che viene prima ma che è più specifica.

- *Nomenclatura*: quella con i 2 dash per i modifier è considerata un'alternativa (https://en.bem.info/methodology/naming-convention/#two-dashes-style)
Io continuo a spingere per questo.

Però è intelligente la cosa di indicare il tipo di modifier nella classe; volendo usare la nomenclatura con i 2 dash si potrebbe scrivere `.block__element--size-medium` o addirittura `.block__element--size_medium` per separare il tipo di modifier dalla sua definizione.

- *Mix*: Non mi convincono. Per fare quello che fa nell'articolo penso sia sufficiente usare un modifier.
Mix: `class="form search"`
Modifier: `class="form form--search"`

Secondo me è pure più intuitivo.

- *Struttura dei file*: Ok separare tutto, ma creare addirittura file per elementi e modifier mi sembra un tantino eccessivo.

- https://en.bem.info/platform/bem-xjst/8/ : Questo è fighissimo

**Comment by davidedistefano** [comment]
Abbiamo fatto un meeting ed il sunto di quello che è uscito è:
- Tutti gli elementi come bottoni, form, ma anche header e footer o sezioni di una pagina, sono componenti. Quando si deve modificare un componente di una specifica classe si possono usare i modifiers (`.block__elem--mod`) dentro lo stesso file. 
- File unico per variabili globali (`variables.scss`) invece più file (es. `colors.scss` o `fonts.scss`).
- Non usare l'underscore davanti ai file scss da importare.
- Usare due volte a capo tra i selettori, a meno che non abbiano proprietà all'interno.
- Evitare di usare `@extend`, anche perché usando i componenti è difficile che nasca la necessità.

**Comment by aldesantis** [comment]
@davidedistefano commento un po' OT, frutto della mia limitata esperienza col design: ma eliminare l'outline non crea problemi di accessibilità?

**Comment by davidedistefano** [comment]
Risorse esistenti ce ne sono:
- https://www.smashingmagazine.com/2018/06/bem-for-beginners/
- https://en.bem.info/methodology/quick-start/

Ma in linea di massima vorrei creare delle linee guida per il front-end da utilizzare per ogni nostro progetto.

Comunque si potrebbe partire dal secondo e il terzo commento in questa issue.
