### ISSUE TITLE
Aggiornare nomenclatura branch

### ISSUE THREAD

**Issue by aldesantis** [nebulab/playbook#68]

**Comment by aldesantis** [comment]
@kennyadsl se vuoi riporta qui il tuo commento così possiamo intavolare una discussione. Per me 💯 aggiornare la nomenclatura, anche perché il prefisso `nebulab/` ha ancora meno senso in progetti dove lavoriamo solo noi.

**Comment by kennyadsl** [comment]
Io inizierei a far decadere la policy `nome-team/nome-funzionalita` in favore di qualcosa di più strutturato e personale. 

Tipo mi sono sempre trovato bene con `nick-github/issue-number/nome-funzionalita` (es. `kennyadsl/1211/login`). 

In questo modo ho sottomano sempre chi è responsabile di quel branch (se dovesse servire fare pulizia e cancellarlo ad esempio saprei a chi chiedere), numero della issue per risalire al problema dal branch (utile anche quando si deve aprire la PR per collegarla facilmente tramite ref) e nome funzionalità che si spiega da solo. Che ne pensate?

**Comment by aldesantis** [comment]
@kennyadsl l'unica piccola modifica che apporterei è il dash invece dello slash tra numero issue e descrizione, es. `kennyadsl/1211-login`. Questo perché di slash già ce ne stanno parecchi se includi anche il nome del remote, quindi non voglio appesantire troppo il nome del branch dando l'impressione che ci sia un'ulteriore gerarchia.

**Comment by elia** [comment]
@kennyadsl il numero è il numero della issue che viene risolta? si può mettere opzionale per i casi in cui non ci sia issue di riferimento?

Poi c'è da considerare anche il caso in cui si lavora in più di uno su un branch, per cui il namespace col nick è fuorviante.

**Comment by kennyadsl** [comment]
> il numero è il numero della issue che viene risolta? si può mettere opzionale per i casi in cui non ci sia issue di riferimento?

Si, dovrebbe essere opzionale. Gestendo i progetti con il Workflow proposto da Nebulab ci dovrebeb sempre essere una issue legata alla PR che si apre, vedi https://github.com/nebulab/workflow/projects/1 . Su questi project ci dovrebbero sempre e solo andare le issue e mai le PR (a meno di casi straordinari).

> Poi c'è da considerare anche il caso in cui si lavora in più di uno su un branch, per cui il namespace col nick è fuorviante.

Questo è un caso limite, nel 99% dei casi la PR è gestita da una sola persona. Sarei cmq d'accordo nel descrivere come comportarsi in questi casi nella pagina. Propongo di usare `nebulab/resto-delle-convenzioni` quando si pensa che si possa lavorare insieme a qualcun altro su un determinato branch.

**Comment by mdesantis** [comment]
Io uso `<username>/<descrizione>`; `<issue-id>` non è male, ma non sempre un branch è legato ad una ed una sola issue

**Comment by kennyadsl** [comment]
> Io uso <username>/<descrizione>; <issue-id> non è male, ma non sempre un branch è legato ad una ed una sola issue; poi se cambia la issue tocca cambiarlo etc.

Quanto è frequente che cambi la issue legata ad una PR? Ti capita spesso?

**Comment by mdesantis** [comment]
Ah ecco leggo ora la discussione sull'opzionale o meno

**Comment by mdesantis** [comment]
Spesso no, però capita; tu dici, rinomini il branch?

**Comment by kennyadsl** [comment]
> tu dici, rinomini il branch?

Si, non si tratta di trovare una cosa che funziona anche con tutti i casi limite ma trovare una cosa molto utile nei casi normali che sono quelli che facciamo più spesso aumentando la produttività. 

Se serve cambiare il nome di un branch tanto lo sappiamo tutti fare e ci vuole poco, ma tanto è talmente raro che in un anno potresti perdere max 10 minuti in totale per fare questa operazione.

**Comment by elia** [comment]
@kennyadsl ma a quel punto devi riaprire la PR, mi pare in passato di aver abbandonato i numerini proprio per questo motivo

**Comment by kennyadsl** [comment]
Anche se ci fosse da riaprire la PR non vedo un grandissimo problema. Se cambia la issue e devi cambiare nome del branch (a me non è mai successo finora) non vedo grossi ostacoli nel chiudere/riaprire una PR.

**Comment by aldesantis** [comment]
Effettivamente neanche a me è mai successo che cambiasse la issue, penso che sia un evento veramente raro.

**Comment by mdesantis** [comment]
Mi avete convinto :)
