### ISSUE TITLE
Santo Patrono

### ISSUE THREAD

**Issue by matteogalliani** [nebulab/playbook#83]
Si deve lavorare il giorno del Santo Patrono della città dove si abita?

Creare una sezione, probabilmente da includere nella sezione [Ferie](https://github.com/nebulab/playbook/blob/master/procedure/ferie-permessi-malattia.md), per rispondere a questa domanda.

**Comment by aldesantis** [comment]
@matteogalliani la risposta alla domanda secondo te qual è? 😄

**Comment by matteogalliani** [comment]
😄non mi ricordavo la regola dal CCNL @aldesantis!
Ecco la regola.
**lavoro in sede legale** Pescara: 10 Ottobre
**sede in sede operativa** Latina: 06 Luglio
**telelavoro** da Remoto: vale il giorno della sede legale, cioè il 10 ottobre

Attulamente non stiamo facendo la chiusura, lasciando libero ognuno di scegliere se lavorare o meno in corrispondenza di questa festività. Tuttavia, visto che il giorno del Santo patrono eventualmente lavorato viene retribuito *(1)* a parte, chiunque si voglia assentare nei giorni sù indicati o nel giorno del Santo patrono della sua città (Es. Sant'Ambrogio 22 Novembre) può tranquillamente prendere un giorno di ferie.


*(1) La retribuzione nel caso una persona lavorasse nel giorno previsto contrattualmente è maggiore di una giornata qualsiasi. Viene considerato lavoro straordinario in un giorno festivo quindi la paga viene maggiorata del 30%*

**Comment by aldesantis** [comment]
@matteogalliani ok! Vuoi aggiungere tu così lo scrivi bene?

**Comment by matteogalliani** [comment]
yep @aldesantis
