### ISSUE TITLE
Aggiungere Workable alla Privacy Policy

### ISSUE THREAD

**Issue by matteogalliani** [nebulab/playbook#90]
In "Strumenti per la raccolta e gestione dei dati personali" c'è [Trello](https://github.com/nebulab/playbook/blob/master/risorse/privacy-policy.md#trello) per la gestione e archiviazione dei candidati a posizioni lavorative. Da sotituire con Workable.

**Comment by aldesantis** [comment]
Workable viene usato per collezionare dati inviati dal sito, quindi andrebbe aggiunto alla PP del sito.
